### ISSUE TITLE
Promregator doesn't start on OpenShift

### ISSUE THREAD

**Issue by martin-schaefer** [promregator/promregator#101]
## Environment
OpenShift Master: v3.11.82, Kubernetes Master:
v1.11.0, docker image promregator/promregator:0.5.7

## Summary / Problem Statement
I tried to run promregator on OpenShift using "Deploy Image" from the web console. But when the pod starts, promregator fails on startup.

![image](https://user-images.githubusercontent.com/11317256/56971983-80049480-6b6a-11e9-9488-2f9083447199.png)

## Observed Behavior
Promregator pod fails to start with the message: /bin/sh: 1: /opt/promregator/promregator.sh: Permission denied.

## Expected Behavior
Promregator should start.

As I am quite new to OpenShift, I probably did something wrong. Does anybody have a running instance of promregator on OpenShift and can give me a hint how to do this? Thanks!

**Comment by eaglerainbow** [comment]
Hi Martin,

welcome to Promregator!
Unfortunately, I have to tell you that I have no clue about OpenShift/Kubernetes in general. Promregator also does not officially support that. That is why you would have to rely on the knowledge of Promregator's community, which still is quite in its infancy.

The only thing that I might contribute here is that `/opt/promregator/promregator.sh` is the [script](https://github.com/promregator/promregator/blob/9ee5ccd2d2a9f8095070b3ac11deaa769d6651b1/docker/data/promregator.sh) which serves as [bootstrapper for Promregator](https://github.com/promregator/promregator/blob/9ee5ccd2d2a9f8095070b3ac11deaa769d6651b1/docker/Dockerfile#L41) in case of the docker image. The [script for building the docker image sets the execution bits](https://github.com/promregator/promregator/blob/9ee5ccd2d2a9f8095070b3ac11deaa769d6651b1/docker/Dockerfile#L35) of that file properly. However, only the user "promregator" (inside the container) is permitted to execute it (user id is 1000 by default) That is why I would suggest to check your configuration with which user is used for starting the docker container. 
Moreover, you should think about how you inject your configuration file into your image: Without a proper `promregator.yaml` file, Promregator won't be worth a penny...

In case you get it running with OpenShift, please don't hesitate to contribute some documentation back to Promregator: also proper (3rd-party provided) documentation is a valuable resource - something which many other's often falsely forget.

**Comment by martin-schaefer** [comment]
I had no sucess yet and decided to run it on Cloud Foundry as of now. There it workes fine so far.

**Comment by eaglerainbow** [comment]
Thanks for the feedback! 
How severe is this issue for you? As I could not be of help, and there are little folks around here, apparently, who might help, I am currently undecided about what to do with this issue.... What do you think?

**Comment by martin-schaefer** [comment]
Thanks for your reply,

Right now I decided to run promregator on Cloud Foundry as we run OpenShift and Pivotal side-by-side. I just installed it today and I am very pleased about the additional labels for space, app and instance making it rock with Prometheus and Grafana!
The fact that I could not run it on OpenShift does not mean something becaus I tried it with just little knowlede about docker and kubernetes. From my pount of view you can close this ticket.
There are just two bullet pints on my "whishlist" for promregator:

- Support selecting apps by cf labels. This would allow to "mark" apps with a label for inclusion in promregator instead of using app names. The app name approach means you must often change promregators config to add specific apps. 
- Add Spring Cloud Config support, See #103 

Probably I can contribute something to this.

Cheers
Martin

**Comment by eaglerainbow** [comment]
> Support selecting apps by cf labels. 

Could I convince you to create a  new issue for that topic? 
We had already similar discussions in other threads/issues, too, but the idea of using cf labels hasn't come up so far. I would like to bring together all involved parties there...

> Add Spring Cloud Config support, See #103

Yes, I already saw so. I am currently thinking about how to make that happen. Partly it's easy, partly I still see some troubles (for example what testability is concerned).

> Probably I can contribute something to this.

You are warmly welcome to do so!
Perhaps already having a clear requirements discussion on the cf labels thing could be very helpful (in the to-be-created issue).

**Comment by eaglerainbow** [comment]
> The app name approach means you must often change promregators config to add specific apps.

You are aware that Promregator

a) supports omitting the `applicationName` attribute, thus selecting all apps in a given space,
and
b) supports `applicationRegex` where you can specify a regular expression for defining which apps in a space shall be scraped?

Moreover, there is also `orgRegex` and `spaceRegex`, which behave similarly for `orgName` and `spaceName` respectively. And you are also able to combine all the regex'ish stuff (and also omission) in all variants...

**Comment by eaglerainbow** [comment]
Just for the record: More information on CF Labels can be found [here](https://docs.cloudfoundry.org/adminguide/metadata.html)

**Comment by eaglerainbow** [comment]
> Probably I can contribute something to this.

You also might want to have a look at [https://github.com/promregator/promregator/wiki/Supporters-Wanted!](https://github.com/promregator/promregator/wiki/Supporters-Wanted!).

**Comment by martin-schaefer** [comment]
> You are aware that Promregator
I am aware of all the options, including regex . But still I think using CF labels (or annotations) would be the proper way to identify the apps to get metrics from. This approach is similar to the whiteboard pattern wich is widely used in service oriented environments and OSGi.

Using app names has the disadvantage to required a name-pattern or to add every's apps name to promregator configuration. This assumes a scenario, where only selected apps should be picked by promregator.

A regex for labels would not be necessary because one is free to define specialized labels like "prometheus-metrices-provider" and can use exact match.

**Comment by eaglerainbow** [comment]
> I am aware of all the options, including regex . But still I think using CF labels (or annotations) would be the proper way to identify the apps to get metrics from.

Then, let's have the proper discussion in #110 about that.

Given the fact that you have raised that issue and as you said

> The fact that I could not run it on OpenShift does not mean something because I tried it with just little knowledge about Docker and Kubernetes. From my point of view you can close this ticket.

I would close this issue here (and refer interested parties to read on in #110).
