### ISSUE TITLE
How to provide promregator.yml for local development without Docker

### ISSUE THREAD

**Issue by thestevenbell** [promregator/promregator#105]
This is a general question, not an issue.  

## Summary / Problem Statement
It's unclear how to provide the configuration promregator.yml file to be able to develop using a jar instead of the docker image.  Where should the config file be when running the jar?

Is there a forum for questions?

**Comment by thestevenbell** [comment]
Moving the promregator.yml file into src/main/resources and running with  
``` java -jar \
  -Dspring.config.name=promregator \
  target/promregator-0.6.0-SNAPSHOT.jar
``` 

was the trick.

**Comment by eaglerainbow** [comment]
Hi Steven,

yes, that is the trick.
Do you think that we should somehow improve the documentation?

We don't have any forum yet. Any suggestions?

**Comment by eaglerainbow** [comment]
> Is there a forum for questions?

It's okay for me to create issues for that (at least for the time being).
Anyway, I personally think that almost every question (not bug reports) coming up, should at least be checked whether documentation should be improved in one or the other way.

**Comment by thestevenbell** [comment]
Sure, makes sense.  In the case of the above question, adding the answer to the documentation would be helpful so adding an issue would help in ensuring this occurs.

**Comment by eaglerainbow** [comment]
Then I'll reopen this issue here until the latter has been done.

**Comment by eaglerainbow** [comment]
Mmhm... I had on my mind that I had written something like that before. Looking again through our documentation, I found https://github.com/promregator/promregator/blob/8c7ada0f6409917d9644bba3aaafa58276ab7cd1/docs/documentation.md#configuration-of-promregator. 

Would that have answered your question already? If no, what is missing?
If yes, did you find it before? If no, why not? Where would have you looked for it?

**Comment by thestevenbell** [comment]
Well, that is quite clear.  Not sure how I missed those instructions - probably saw the quickstart directions and went there first.  We originally were running the docker image but now are debugging the OAuth2XSUAA OAuth process so are using a locally compiled jar.

**Comment by eaglerainbow** [comment]
>  Not sure how I missed those instructions - probably saw the quickstart directions and went there first. We originally were running the docker image 

Okay, perhaps we have then to provide some cross-reference to the full documentation page again. 

> but now are debugging the OAuth2XSUAA OAuth process so are using a locally compiled jar.

Be careful with that. The coding there is quite tricky and was implemented by me for a very special case. It is quite possible that this does not work for a more general case.
Therefore, please feel free to raise another issue explaining your use case - and I would be very willing to help clarifying whether it is covered or not..

**Comment by eaglerainbow** [comment]
With 0ea68b10c396ea765b93edda12d9bbfbb8fb8179 I tried to improve the quickstart page a little, giving another hint back to the "standard configuration pages". I don't know whether that really would have helped you, but it's an attempt at least.
If you have a better idea what could have helped you, please feel free to comment here and reopen the issue!
