### ISSUE TITLE
Additional CF login mechanism per space

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#111]
Hi @eaglerainbow,

now i'm coming with a kind of weird "feature" request :D

We need a different mechanism for the login to the CF Api.
For security reason (thats different topic :D )  we use now one login per space with rotating keys with can be fetched internally and only valid for a specific amount of time.

I've got it managed already to use this mechanism at least for a single space by exchanging the normal PasswordGrantTokenProvider.
But if i understand the code correct we would need to have a single cfReactorClient for every set of credentials?

Maybe you have a good idea how we could implement such a mechanism? or would you suggest to have one promregator per space? 

Thanks for your help

**Comment by eaglerainbow** [comment]
Uhh... that's a rather complex case.
The biggest problem is the fact that each authentication only provides authorization for a single space. Promregator isn't designed to handle multiple authentication tokens for different domains (here: spaces). And I don't see, how we could change that easily. As of now the only option I see is to have a Promregator instance for each space (which I know isn't the answer you hope for). 

About how many spaces are we talking?

> But if i understand the code correct we would need to have a single cfReactorClient for every set of credentials?

Yes, that would be it in a nutshell: And today, all the caches assume that there is a single instance of  cfReactorClient to fetch from. Making that dynamic would not be rocket science, though, but you would have to derive the `cfReactorClient` from the context (here: the space). However, for you it would be spaces now; for another user it might be the org. For even another one it'll be a set of spaces or so. 
In the end this would mean that we would have to introduce something like a "CF Accessor identifier" or so - making it for each target configured to say with which "CF Accessor Identifier" the data shall be fetched. The problem then, however, is with uniqueness: What happens, if you enter different CF landscapes with different credentials, but the orgNames and/or spaceNames (the internal IDs most likely won't be affected by this, as they are GUIDs) could easily clash. To make the caches handle this case would mean to pack the CF Accessor Identifier also into the key of all caches. In the end, this means making almost everything upside down. 

>  we use now one login per space with rotating keys with can be fetched internally and only valid for a specific amount of time.

That sounds 2FA-ish to me.
If that is the case, I should warn you here: if you have to provide the rotating credentials manually (e.g. hardware token generator), then don't even *think* that you want to have such a thing with Promregator: Promregator has to re-fetch authentication tokens after a while (due to JWT expiry) - and may need the original credentials for that then. This might happen in the middle of the night when you are even not near your machine.

**Comment by eloo** [comment]
Okay,
>  As of now the only option I see is to have a Promregator instance for each space

yes that is more or less what i was expecting :D 

> About how many spaces are we talking?

depends on the team, but i'm thinking about 3 to 6 spaces per team (atm one team has one promregator)

> That sounds 2FA-ish to me.

No its not directly 2FA but a morelike custom mechanism. Further this problem is already solved own our side.

**Comment by eaglerainbow** [comment]
> yes that is more or less what i was expecting :D

Well, it's the sad truth 😞 

> depends on the team, but i'm thinking about 3 to 6 spaces per team (atm one team has one promregator)

That's bad, as it's exactly close the break-even point: It's enough that it might become ugly for a team, but it's also not enough to say, hey, we really must fix that fundamentally.
Unfortunately, I fear that this also won't be an easy thing to do in the current design of Promregator: it would mean that we have to support multiple [CFAccessor](https://github.com/promregator/promregator/blob/8ab4d27a0a6415fd1ae43f1dd419d080d5a2c056/src/main/java/org/cloudfoundry/promregator/cfaccessor/CFAccessor.java)s. In turn, this means that the target must reserve-define from which CFAccessor the data shall be fetched. Thus, the configuration must provide an option to configure multiple CFAccessors. In your case it might be sufficient to have several CFAccessors, but all of them would point to the same API endpoint (as you only want to change the logon credentials). This would at least permit to keep the caches free of the reference to the CFAccessor, as the space/org/... identifiers still would be kept unique (which would save a lot of effort for the necessary refactoring). However I fear that the next one will come very soon also asking: "I have two CF platforms installed, why can't Promregator support scraping it with one instance, if it already supports multiple credentials". In short: not also considering cf.api_host looks inconsistent as well. 

What's the timeline we are talking about here? When will your "custom credentials" go live?

**Comment by eloo** [comment]
yes i totally understand you and its okay to have multiple promregators per team for us. 
atm i'm nearly done with my workaround where i use a custom tokenprovider and after the key retention im creating a new one. this works so far so good but sadly i'm facing a memory leak.
it looks like my connections are not cleaned up properly :/ 

Generally speaking i have exchanged the tokenProvider method and adapted the resetClient method like this 
```
@Scheduled(fixedRate = 25 * 60 * 1000, initialDelay = 60 * 1000)
private void resetCloudFoundryClient() throws ConfigurationException {
    ProxyConfiguration proxyConfiguration = this.proxyConfiguration();
    if (cloudFoundryClient != null) {
        ((DefaultConnectionContext) cloudFoundryClient.getConnectionContext()).dispose();
    }
    ConnectionContext connectionContext = connectionContext(proxyConfiguration);
    PasswordGrantTokenProvider tokenProvider = this.tokenProvider();

    this.cloudFoundryClient = this.cloudFoundryClient(connectionContext, tokenProvider);
}
```
but it seems that i'm still getting a new threads of this  "cloudfoundry-client-nio-X" 
the interesting thing is that this doesn't happen in the 25 minutes interval. it only appears when the API is going to be in maintenance and comes back
do you have maybe an idea? 

The timeline for that is already over :D but atm we live with a workaround

**Comment by eaglerainbow** [comment]
Are you really sure that this is a real resource leak?

Also this `dispose()` approach looks quite rigorous to me. 
Remember that you have caches, which refer to living `Mono`s which still may contain a reference to `cloudFoundryClient` at that point when the Fluxes/Monos hat been created. As long as they are in the cache, you can't kill them, as these are hard Java references. 
The thing that they are only happening in the maintenance mode is strange, though. This would hint to an issue [with the automatic displacement I had implemented](https://github.com/promregator/promregator/blob/8ab4d27a0a6415fd1ae43f1dd419d080d5a2c056/src/main/java/org/cloudfoundry/promregator/cfaccessor/CFAccessorCache.java#L304) for you recently. However, I can't see right now either, where this should be coming from.

**Comment by eaglerainbow** [comment]
https://github.com/cloudfoundry/cf-java-client/blob/caa1cb889cfe8717614c071703d833a1540784df/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/_DefaultConnectionContext.java#L42 indicates that you are screwing there at the right spot with your `dispose()` thing. 

The only place in Promregator where another set of connections may be created is with https://github.com/promregator/promregator/blob/8ab4d27a0a6415fd1ae43f1dd419d080d5a2c056/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L205 
However, that would be calling the desired `dispose()` logic. 
So, I am currently also quite clueless from where this should come. 

As an idea perhaps for a workaround: Do you really must create a new connectionContext? Can't you just reuse the old one?
I was just very conservative with the `resetCloudFoundryClient()` because I did not know what else was broken - and thus I tried to get rid of everything that looked like a connection to the CF CC.
In your (maintenance) case, the HTTP connection itself isn't broken. So perhaps, for your custom case it might be sufficient keep the `connectionContext` alive...

**Comment by eloo** [comment]
Yes its a resource leak because the threads are increasing every time which ends up in unlimited threads of the same typ.
![image](https://user-images.githubusercontent.com/2631895/61270801-03fe0e00-a7a3-11e9-83e1-d6be49037769.png)

Related to the question if i need to dispose the client, i've tried different approaches and came up with the one of the client disposal and one with reuse the connection context.
First approach with full disposal resulted in memory leak because of the thread.
Second approach results in unrecovering from maintenance.

The weird thing about the recovering and also the thread leak is that also if i mock the api and simulate the maintenance mode i cant reproduce it locally (mocked as much is a can and the app responded as expected).

But i've just figured out that when i use the debugger and "hold" the execution i get the ssl handshake timeout. With this exception i can reproduce the real behaviour with thread increase and so on. 

A far better news is that i was capable of getting the reuse of the connection context to work. It looks like the recovering after the endpoint maintenance was influenced by the caches. I've implemented a step to invalidate the caches which is done AFTER the api has recovered. 
Like this 
```
.subscribe(response -> {
                    if (response == ERRONEOUS_GET_INFO_RESPONSE) {
                        errored = true;
                        log.warn(String.format("Error in watchdog found: %s", response.toString()));
                        log.warn("Invalidating caches");
                        InvalidateCacheEndpoint cache = ctx.getBean(InvalidateCacheEndpoint.class);
                        cache.invalidateCache(true, true, true, true);
                        try {
                            // Note that there is no method at this.cloudFoundryClient, which would permit closing the old client
                            this.resetCloudFoundryClient();
                        } catch (ConfigurationException ce) {
                            log.warn("Unable to reconstruct connection to CF CC", ce);
                        }
                    } else if (errored) {
                        log.warn("Invalidating caches after api has recovered");
                        cacheEndpoint.invalidateCache(true, true, true, true);
                        errored = false;
                    }
                });
```

Maybe thats a hint that the errored responses are also cached somehow?

**Comment by eaglerainbow** [comment]
> But i've just figured out that when i use the debugger and "hold" the execution i get the ssl handshake timeout. With this exception i can reproduce the real behaviour with thread increase and so on.

For me this is an indicator that we are talking here about a cf-java-client issue -- or even a netty-reactor issue that you just detected. As I have only little experience in that field there (I wonder how people are able to implement correct consumers of netty in general), I'd suggest that you might address that topic to one of those projects:
* https://github.com/netty/netty
* https://github.com/cloudfoundry/cf-java-client

> Maybe thats a hint that the errored responses are also cached somehow?

I can't really make sense out of that so far: 
* As you can see in https://github.com/promregator/promregator/blob/8ab4d27a0a6415fd1ae43f1dd419d080d5a2c056/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L89 Promregator itself only keeps the reference of the `cloudFoundryClient` (which in turn references the connectionContext) locally in the implementation. The only case where which *might* have a reference, are the results of the operations called by `ReactiveCFAccessorImpl`
* Those `Mono`s are typically stored in an instance of [`CFAccessorCache`](https://github.com/promregator/promregator/blob/8ab4d27a0a6415fd1ae43f1dd419d080d5a2c056/src/main/java/org/cloudfoundry/promregator/cfaccessor/CFAccessorCache.java). With your call to 
```java
InvalidateCacheEndpoint cache = ctx.getBean(InvalidateCacheEndpoint.class);
cache.invalidateCache(true, true, true, true);
```
   you more or less just trigger the CFAccessorCache to clean up all the data in there (see also https://github.com/promregator/promregator/blob/82244e1d3ccb7aa6675dcd0f9a29cf50a9e92af1/src/main/java/org/cloudfoundry/promregator/endpoint/InvalidateCacheEndpoint.java#L30). However with the cases like https://github.com/promregator/promregator/blob/b2c9fcbbe7019529bc332647cae77c790d70958f/src/main/java/org/cloudfoundry/promregator/cfaccessor/CFAccessorCache.java#L126, the records which are prone to  your maintenance error case are automatically discarded from the cache. 

Are you sure that you are really based on branch `issue-96-ccfcdowntime-workaround` and not on `master`?

BTW: there is one more cache that you also flush: It's the TargetResolver's cache. The latter you may find at https://github.com/promregator/promregator/blob/b2c9fcbbe7019529bc332647cae77c790d70958f/src/main/java/org/cloudfoundry/promregator/scanner/CachingTargetResolver.java . However I would not know how that one may store a transitive reference to a connectionConntext: The cache handles instances of type `Target` (key) and `ResolvedTarget` (value). Both of them mainly consistent only of strings.  It thus might be an interesting experiment, if you would set the last invalidation parameter of the `InvalidateCacheEndpoint` (see also https://github.com/promregator/promregator/blob/82244e1d3ccb7aa6675dcd0f9a29cf50a9e92af1/src/main/java/org/cloudfoundry/promregator/endpoint/InvalidateCacheEndpoint.java#L34 ) to "false". If you then can reproduce the connectionContext issue again, then you know that it must come from the TargetResolver cache. If not, you have ruled it out completely.

**Comment by eloo** [comment]
Ah okay, yes i've already had a short look at netty and cf-client-java and for me also a problem is that cf-client-java is really outdated in relation to the netty libs. it also looks like the cf-client-java is not really actively maintained at the moment :/ 

> Are you sure that you are really based on branch issue-96-ccfcdowntime-workaround and not on master?

I'm sure i'm using your master branch :D totally missed that branch. maybe i will try this branch in the next days.

> It thus might be an interesting experiment, if you would set the last invalidation parameter of the InvalidateCacheEndpoint ... to "false".

yes of course i can test it.

**Comment by eaglerainbow** [comment]
> I'm sure i'm using your master branch :D totally missed that branch. maybe i will try this branch in the next days.

Well, that explains a lot:
* Without the corrections on the issue-96-* branch, the org/space/application caches can be polluted with (stored) instances, which are broken from the maintenance message.
* Those entries in the cache don't work anymore, as they cached the error message. They would only be displaced after the timeout has occurred.

In a nutshell, your modifications trying to call the invalidation of the cache intelligently only tries to fix an issue, which I have already fixed on the issue-96-* branch. Along these lines, you apparently also caught yourself somehow in a resource leak of the connections. 

In short, before chasing more phantoms, I'd highly suggest to go to the branch `issue-96-ccfcdowntime-workaround`.

**Comment by eloo** [comment]
@eaglerainbow 
i've tested the issue-96-ccfcdowntime-workaround branch and it looks very promising. 
I don't see any issues so far with this branch. thanks for the hint!

**Comment by eaglerainbow** [comment]
Okay, given that statement, I'd suggest to close this ticket here and follow up the rest on this matter at #96. 
In case anything is still needed on this topic, please feel free to reopen this issue here.
