### ISSUE TITLE
One app multiple routes - only one has metrics

### ISSUE THREAD

**Issue by jensbaitingerbosch** [promregator/promregator#114]
## Environment
cf api:  2.120.0
promregator: 0.5.7

## Summary / Problem Statement
We have an app that has two routes, One facing the internet that does not provide any metrics and is only reachable if the client provides a client certificate (otherwise the ssl handshake will fail). The other route is internal and provides metrics (and other internal api). 

## Observed Behavior
When we let Promregator scrape the metrics it uses the external route and fails with an ssl exception, as the handshake fails. 

## Expected Behavior
There is a possibility that Promregator "selects" the correct route or it can be configured:
- it probes all routes and ignores errors, as long as it can successfully scrape metrics from one of the apps routes (maybe caches the successful route so it does not repeat the error and polutes the log files )
- there is a possibility to configure the order of routes e.g. 
  1. `.*\.internal\.mydomain\.com`
  1. `.*\.external\.mydomain\.com`
  maybe with regex 
- possibility of blacklisting routes e.g. 
  - .*\.external\.mydomain\.com`

**Comment by jensbaitingerbosch** [comment]
Found the solution in #91, could you please add the configuration `preferredRouteRegex` to the documentation?

**Comment by jensbaitingerbosch** [comment]
Addition note, what I just found out, it is available from 0.5.8-rc1

**Comment by eaglerainbow** [comment]
> could you please add the configuration preferredRouteRegex to the documentation?

I certainly will, but I still need someone to confirm #91 first that the scenario is working for him. Otherwise (documentation follows the release strategy in Promregator) I don't want to release a new version (as the mainline is currently dirty with that - and some other stuff).

**Comment by jensbaitingerbosch** [comment]
For me it actually worked for me (but after I noticed #115, I rolled back to a patched version of the 0.5-branch
