### ISSUE TITLE
Need to work around CF v2 endpoint bug when using v3 endpoints to deploy

### ISSUE THREAD

**Issue by checketts** [promregator/promregator#139]
## Environment
cf api version: 2.142

## Summary / Problem Statement
When an app is deployed using the 'rolling' deployment strategy Promregator can no long call it. This is due to a [bug in CF (cloud_controller_ng#1523)](https://github.com/cloudfoundry/cloud_controller_ng/issues/1523) making the /v2/space endpoint return the app's process GUID instead of the app's own GUID.

## Observed Behavior
Promregator reports 404s when calling the Prometheus endpoint for the give app instance

## Expected Behavior
It should be able to continue collecting metrics.

I'll begin working on a local workaround and submit a PR shortly (since we are busted at this point!). Since the v2 endpoints are being sunsetted, is there any concerns if I migrate directly to the v3 endpoints?

**Comment by eaglerainbow** [comment]
Hi,

Thanks for reporting it!
Just from reading it (not having checked anything further yet), I am wondering about that you should "feel" the bug you mentioned with Promregator. What's your cache timeout configuration setting? Is the app cache configuration really so aggressive with you? How long are your push operations?

W.r.t. to v2 vs. v3 endpoints: My current gut-feeling is that Promregator will require to support v2 for yet a longer time, as many platforms out there don't have proper support for v3 yet (or at least with those I am working with them). However, I would feel comfortable if there was an optional configuration option, which enabled "v3 mode" explicitly (then the user can decide whether his platform is v3-okish enough for him). But perhaps this wouldn't be subject to a PR in first place, but could be added later on (if you ensure that the modes are switchable).

**Comment by eaglerainbow** [comment]
argh! I got it: after deployment the process GUID stays in there for the summary. 🙄

**Comment by eaglerainbow** [comment]
In a nutshell, I do see two options:
* Have a "v3 mode" where we switch at least the summary-retrieval part (see proposal by @checketts above),
or 
* pull out the old pre-summary coding (i.e. [`rel-0.4` level](https://github.com/promregator/promregator/blob/rel-0.4/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java)), where I also had introduced the "v3 process" stuff (at those times more by error). It could serve as a basis for a workaround implementation.

Unfortunately, as it's night time (local time) for me, I can't have a more thorough look at this case right away.

**Comment by eaglerainbow** [comment]
Just to note it down: I got another idea of an approach for this issue: As we know what's provided, we may also try to "reverse correct" the values as workaround - i.e. Check if the ID really is an app ID or a process ID. And iff it is a process id, we fetch the process ID metadata, replacing the wrong id with the correct one (internally only). 

PS: Yes, I saw the PR for this issue. I will have a closer look at it tonight. From the first sight I have an idea where this correction *could* potentially break things, but I want to test and look it more thoroughly before claiming anything.

**Comment by eaglerainbow** [comment]
> Just to note it down: I got another idea of an approach for this issue: As we know what's provided, we may also try to "reverse correct" the values as workaround

I checked this approach and it would be possible to send a `/v3/processes/:guid:` request with the id of the space's summary. In case that the guid could be resolved, the app id can be found at `relationship.app.data.guid` in the response. If the guid cannot be resolved, the error message returned would be 
```json
{
   "errors": [
      {
         "detail": "Process not found",
         "title": "CF-ResourceNotFound",
         "code": 10010
      }
   ]
}
```

However, the suggestion made in PR #140 seems to be better: My approach would mean `n` such requests for every space's summary calls (where `n` is the number of apps in the space). Those requests could be answered by the CFCC very easily, but already the network latency is ugly by itself. 

The approach proposed in #140 just uses data that has already been scraped anyway. So not a single additional CFCC request is necessary (and it's shorted and by far not ugly at all).

**Comment by checketts** [comment]
Can you kick off the build again?
