### ISSUE TITLE
Promregator Does Not Handle Expired Refresh Token

### ISSUE THREAD

**Issue by mickey-hill** [promregator/promregator#162]
## Environment
promregator 7.2

## Summary / Problem Statement
Promregator does not handle the expiration of the OAuth refresh token.  In addition to losing the ability to interact with the CF API, it causes each iteration of the  ReactiveCFAccessorImpl.connectionWatchdog to fail which will destabilize Promregator (see #161).  The call to ReactiveCFAccessImpl.resetCloudFoundryClient() within connectionWatchdog in this case is not causing a new refresh token to be acquired.

Interestingly, calls to ReactiveCFAccessImpl.resetCloudFoundryClient() for other failures in ReactiveCFAccessorImpl.connectionWatchdog prior to the refresh token expiring (e.g. a random timed-out call to the CF API) cause a new OAuth refresh token to be retrieved.

It seems as though the expired refresh token could be disrupting the resetCloudFoundryClient sequence before a new one is acquired.

## Observed Behavior
Promregator does not fetch a new refresh token before (or after) it expires (except in the error handling of unrelated issues as described above).  It cannot interact with the CF API and becomes destabilized as per #161.

## Expected Behavior
A new refresh token should be retrieved prior (or immediately after) one expires.  Ideally, this would not rely on a ReactiveCFAccessImpl.resetCloudFoundryClient() error since it is a predictable scenario.

**Comment by checketts** [comment]
The infinite retry I mentioned in https://github.com/promregator/promregator/issues/161#issuecomment-591700809 fixes this as well (the retry was in refreshing the token)

Please try it with version 0.7.3

**Comment by eaglerainbow** [comment]
Found also https://github.com/cloudfoundry/cf-java-client/issues/775, which is talking about token handling in general, but not about refresh token in particular. 
From what I read there,  I'd assume that handling of the refresh token (if not persisted for later) is done by cf-java-client (in particular by `PasswordGrantTokenProvider`). Also from an abstraction layer perspective, this isn't really the business of the application. In fact it is done by [`AbstractUaaTokenProvider`](https://github.com/cloudfoundry/cf-java-client/blob/ed9e4f102089a0a8a3b01b4cdda152fba0121d43/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java#L262
).

**Comment by eaglerainbow** [comment]
I do not believe that (besides the problem solved with promregator 0.7.3), the problem you face is related with Promregator only. Instead, it appears to me that your issue is much more fundamental and resides in cf-java-client. 

> Promregator does not handle the expiration of the OAuth refresh token.

Do you have any evidence for that claim? If yes, I think it would be valuable to create an issue at https://github.com/cloudfoundry/cf-java-client/issues.

**Comment by mickey-hill** [comment]
Refresh token is refreshed when expired in 0.7.3.

Thank you!

**Comment by eaglerainbow** [comment]
I assume that this solves your issue.
If not, please feel free to speak up/reopen this issue.
