### ISSUE TITLE
Upgrade library versions address vulnerable Third Party Dependancies in 0.7.5 which is still based on Spring Boot 2.1.x

### ISSUE THREAD

**Issue by warlockza** [promregator/promregator#179]
The following dependancies in 0.7.5 need to be updated as they have been identified to have vulnerabilities

org.apache.tomcat.embed:tomcat-embed-core:9.0.30

can be fixed by setting <tomcat.version>9.0.31</tomcat.version> in the pom.xml under properties

com.fasterxml.jackson.core:jackson-databind:2.9.10.2

should be upgraded to 

com.fasterxml.jackson.core:jackson-databind:2.9.10.4

io.netty:netty-codec:4.1.45.Final 

should be upgraded to

io.netty:netty-codec:4.1.46.Final

If we could please get a new version 0.7.6 released that addresses these issues, that would be great

**Comment by checketts** [comment]
All these will be addressed by upgrading to Spring Boot `2.2.6.RELEASE`

Tomcat: 9.0.33
Jackson: 2.10.3
Netty: 4.1.48.Final

**Comment by warlockza** [comment]
But 0.7.x  is still on Spring boot 2.1... Its only 0.8.x that is on 2.2

**Comment by warlockza** [comment]
Thats not to say we shouldnt be upgrading 0.8.x to 2.2.6 as well

**Comment by eaglerainbow** [comment]
spring-boot `2.1.31.RELEASE` bumps to 
`org.apache.tomcat.embed:tomcat-embed-core:9.0.31`  -> okay
`com.fasterxml.jackson.core:jackson-databind:2.9.10.2` -> too low
`io.netty:netty-codec:4.1.45.Final`  -> too low.

**Comment by eaglerainbow** [comment]
I am trying to build a new consistent 0.7.x version with ae241749bfabd55f950cf6dd22caaf9536dee1ec, but this is more tricky than I thought.

**Comment by eaglerainbow** [comment]
Quality verification is currently running through the build infrastructure. We got updates in the SecDep Tool - if this happens, processing them usually  takes 30+ mins. => Will look at it some time later.

**Comment by warlockza** [comment]
Could we please upgrade tomcat to 9.0.33?

**Comment by eaglerainbow** [comment]
What's on your mind? Any special CVE?

**Comment by eaglerainbow** [comment]
BTW: Release 0.7.6 is already created a bundle-signed (can't reopen it anyway).

**Comment by warlockza** [comment]
No its fine - just wanted to move to newer versions
Spring boot 2.1.14 is near immenent (Will probably be released within a week)

It uses

<tomcat.version>9.0.34</tomcat.version>
<netty.version>4.1.49.Final</netty.version>
<jackson.version>2.9.10.20200411</jackson.version>

**Comment by eaglerainbow** [comment]
I'd be totally fine to create another 0.7.7 then with spring-boot 2.1.14. The current state on the branch `rel-0.7` doesn't look nice anyway. I'd like to get away from that drug as well. 

BTW: 0.7.6 is there now.

**Comment by eaglerainbow** [comment]
Does that solve it for you (if yes, I'd close this issue here)?

**Comment by eaglerainbow** [comment]
BTW for the record:  master has been bumped to spring-boot 2.2.6  with ab51b294266cbc55800f61fb76d49a40a4f15a06. Double maintenance done to `simplifiedProm` as well (82168b208e9a7552e9bf78b3b15343649171bc5e).

**Comment by warlockza** [comment]
All good - feel free to close. Thanks for the quick turn around !

**Comment by eaglerainbow** [comment]
Thanks.
You are welcome!
