### ISSUE TITLE
Deployment of 0.8.0?

### ISSUE THREAD

**Issue by tlkamp** [promregator/promregator#187]
I have been running the v0.8.0-rc2 version of Promregator in production since it was "released" as a release candidate and it is working wonderfully. Would it be possible to get a full release of the v0.8.0 created?

**Comment by eaglerainbow** [comment]
checking...

**Comment by eaglerainbow** [comment]
Got some minor troubles with the delivery infrastructure. 
I need to have a look at this topic tomorrow again.

**Comment by eaglerainbow** [comment]
Just released: https://github.com/promregator/promregator/releases/tag/0.8.0

Have fun!

**Comment by tlkamp** [comment]
@eaglerainbow Thank you so much!
