### ISSUE TITLE
Inconsistent Unit test failure

### ISSUE THREAD

**Issue by warlockza** [promregator/promregator#225]
## Summary / Problem Statement
Test Failure
## Observed Behavior
Random failure of Unit Test AutoRefreshingCacheMapTest.testAutoRefresh() 

On the assertion at line 95

`Assertions.assertEquals("initial", subject.get(testkey));`

## Expected Behavior
The test should consistently pass

This test will more than likely fail more times than not - depending on how much cpu is available at the time

- Fundamentally the test is adding a value to the map
- Asserting that it exists and contains the initial value
- waiting for the refresh to happen
- Asserting that it exists and contains the refreshed value

However, while trying to get to the bottom of this, I noticed that the value will be refreshed almost immediatly rather than waiting for the refresh duration.

This is because on line 241 in the method run() we can see that 

`this.refreshMap();`

is called, immediatly .. the delay is only in play AFTER the first time that this.refreshMap(); has run, which basically means there is a very tiny window when the unit test could succeed after there refresher thread has started but before this.refreshMap(); was called...

By changing

```

while (this.shouldRun) {
	try {
		this.refreshMap();
	} catch (Exception e) {
		log.warn("Unexpected exception was raised in Refresher Thread for AutoRefreshingCacheMap", e);
		// fall-through is expected!
	}
	final long sleepDuration = Math.min(500, Math.min(this.map.expiryDuration.toMillis(), this.map.refreshInterval.toMillis()));
	try {
		Thread.sleep(sleepDuration);
	} catch (InterruptedException e) {
		// received signal; check if something has to be done
		log.info("Stopping RefresherThread");
		Thread.currentThread().interrupt();
	}
}
```
to 
```

while (this.shouldRun) {
        final long sleepDuration = Math.min(500, Math.min(this.map.expiryDuration.toMillis(), this.map.refreshInterval.toMillis()));
	try {
		Thread.sleep(sleepDuration);
	} catch (InterruptedException e) {
		// received signal; check if something has to be done
		log.info("Stopping RefresherThread");
		Thread.currentThread().interrupt();
	}
	try {
		this.refreshMap();
	} catch (Exception e) {
		log.warn("Unexpected exception was raised in Refresher Thread for AutoRefreshingCacheMap", e);
		// fall-through is expected!
	}
}
```

ie moving the delay to run before, this.refreshMap(), this test seems to now consistently pass, (as do all other tests)

Is there anything I am missing or a specific reason why the delay was after the first refresh?

**Comment by eaglerainbow** [comment]
Having had a look at your case again, I have to say: kudos!
Background to my reluctance to work on this issue was that I knew that this unit test would soon go away (but in fact had bullied me for such a long time as well 😀 ).

> Is there anything I am missing or a specific reason why the delay was after the first refresh?

No, after thoroughly reading your commands and studying the logic again, you are completely right.
I have incorporated your suggestion into the (old*) mainline with a34d6496cced9e35b341b4996b9114e7b7b409f4

* For the sake of completeness: Note that this unit test exists in the 0.x.y series only and was removed with 1.0.0. The AutoRefreshingCacheMap was replaced by our CaffeineCache there.
