### ISSUE TITLE
Support for CFCC API V3 is needed

### ISSUE THREAD

**Issue by eaglerainbow** [promregator/promregator#228]
## Summary / Problem Statement
Support for CFCC API V2 endpoints is fading out. 

## Observed Behavior
Promregator only supports CFCC API V2.

## Expected Behavior
CFCC API V3 is there and usable. Promregator (in a new version) should make use of it

**Comment by eaglerainbow** [comment]
This will have to end up in a major version bump 😞

**Comment by eaglerainbow** [comment]
😢 This "gettting rid of all /v2/* endpoints" is much more complicated than I thought initially: https://github.com/cloudfoundry/cf-java-client/issues/1160#issuecomment-1399340483

**Comment by checketts** [comment]
Oh yeah I recall inplementing a v3 getInfo in my brancha s well:  https://github.com/checketts/promregator/blob/lite-kotlin/src/main/java/org/cloudfoundry/promregator/lite/cfaccessor/ReactorInfoV3.java

**Comment by checketts** [comment]
That is good that we can work around the Java client shortcomings.

**Comment by eaglerainbow** [comment]
> Promregator is already partially using V3 for all the annotation based filtering, might need to do more of these solutions in order to support the lacking endpoints in the CF Java Client.

It's even more, @braunsonm. With the newest Promregator V1 all calls are already migrated to CF API V3. I also reused your `ReactorInfoV3` with some minor adoptions for that.
The only thing missing was that `/v2/info` endpoint, which [turned out to be not really of a problem](https://github.com/cloudfoundry/cf-java-client/issues/1160#issuecomment-1400282862).
I think, from that front, we are currently in a rather good shape.

**Comment by eaglerainbow** [comment]
After having run 1.0.0-rc* in a semi-productive environment, I finally decided to release [Promregator v1.0.0](https://github.com/promregator/promregator/releases/tag/v1.0.0) just a couple of minutes ago. The new version also includes support for the CFCC API V3 environment.
