### ISSUE TITLE
Request to add __scheme__ promregator.discovery.scheme parameter

### ISSUE THREAD

**Issue by dmarmugi** [promregator/promregator#231]
## Environment
Promregator v0.9.1, running the jar directly in Cloud Foundry on api version 3.115.0
Using /discovery endpoint and [http service discovery](https://prometheus.io/docs/prometheus/latest/http_sd/#http_sd-format)

## Summary / Problem Statement
- This deployment of Cloud Foundry only allows HTTPS/443 ingress. 
- By default, Prometheus http_sd scrapes on http, not https. So it tries to scrape (note the protocol) http://<promregator>:443/singleTargetMetrics/... which fails: `Get "http://<promregator-instance>:443/singleTargetMetrics/31b8a81e-7b44-41f7-a24d-d2e337849536/1": EOF`

- It's possible to work around this, but it requires coordinating changes between the Prometheus scrape config and Promregator:
- * set `promregator.discovery.port: 443`
- * in Prometheus, explicitly set the scheme on the scrape_config: 
```yaml
scrape_configs:
  - job_name: "cf_promregator"
    scheme: https
    http_sd_configs:
      - url: https://<promregator>/discovery
        refresh_interval: 15m
```

## Observed Behavior
Calling /discovery returns an unscrapable URL without a coordinating change in Prometheus:
With a prometheus config like:
```yaml
scrape_configs:
  - job_name: "cf_promregator"
    http_sd_configs:
      - url: https://<promregator>/discovery
        refresh_interval: 15m
```

And /discovery endpoint returning targets like: 
```json
[
  {
    "targets": [
      "<promregator>:443"
    ],
    "labels": {
      "__meta_promregator_target_path": "/singleTargetMetrics/b383b9da-7fc5-49d5-8405-ee3a37a942b5/0",
      "__meta_promregator_target_orgName": "org",
      "__meta_promregator_target_spaceName": "config",
      "__meta_promregator_target_applicationName": "configserver",
      "__meta_promregator_target_applicationId": "b383b9da-7fc5-49d5-8405-ee3a37a942b5",
      "__meta_promregator_target_instanceNumber": "0",
      "__meta_promregator_target_instanceId": "b383b9da-7fc5-49d5-8405-ee3a37a942b5:0",
      "__metrics_path__": "/singleTargetMetrics/b383b9da-7fc5-49d5-8405-ee3a37a942b5/0"
    }
  },
...
```

Scraping fails: `Get "http://<promregator-instance>:443/singleTargetMetrics/b383b9da-7fc5-49d5-8405-ee3a37a942b5/0": EOF`

## Expected Behavior
It's possible to provide a `__scheme__` label in the individual `targets` which controls how Prometheus connects. Support for this would enable resolving this configuration issue entirely on the Promregator side, reducing downtime or the need for coordinating config changes. 

I have a tentative change working locally which works by adding a config parameter `promregator.discovery.scheme` and making a handful of changes in `DiscoveryEndpoint.java`. I'd be happy to fully flesh it out (tests, docs, etc.) if you'd like to proceed. 

The below change adds a `__scheme__` label to the `/discovery` targets, telling Prometheus to scrape using the configured protocol:
```json
[
  {
    "targets": [
      "<promregator>:443"
    ],
    "labels": {
      "__meta_promregator_target_path": "/singleTargetMetrics/b383b9da-7fc5-49d5-8405-ee3a37a942b5/0",
      "__meta_promregator_target_orgName": "org",
      "__meta_promregator_target_spaceName": "config",
      "__meta_promregator_target_applicationName": "configserver",
      "__meta_promregator_target_applicationId": "b383b9da-7fc5-49d5-8405-ee3a37a942b5",
      "__meta_promregator_target_instanceNumber": "0",
      "__meta_promregator_target_instanceId": "b383b9da-7fc5-49d5-8405-ee3a37a942b5:0",
      "__metrics_path__": "/singleTargetMetrics/b383b9da-7fc5-49d5-8405-ee3a37a942b5/0",
      "__scheme__": "https",
    }
  },
```

```diff
diff --git a/src/main/java/org/cloudfoundry/promregator/endpoint/DiscoveryEndpoint.java b/src/main/java/org/cloudfoundry/promregator/endpoint/DiscoveryEndpoint.java
index 2b588801..b51d15e7 100644
--- a/src/main/java/org/cloudfoundry/promregator/endpoint/DiscoveryEndpoint.java
+++ b/src/main/java/org/cloudfoundry/promregator/endpoint/DiscoveryEndpoint.java
@@ -37,6 +37,9 @@ public class DiscoveryEndpoint {
 	
 	@Value("${promregator.discovery.port:0}")
 	private int myPort;
+
+	@Value("${promregator.discovery.scheme:#{null}}")
+	private String myScheme;
 	
 	@Value("${promregator.discovery.ownMetricsEndpoint:true}")
 	private boolean promregatorMetricsEndpoint;
@@ -49,13 +52,14 @@ public class DiscoveryEndpoint {
 		private String applicationId;
 		private String instanceNumber;
 		private String instanceId;
+		private String scheme;
 
 		public DiscoveryLabel(String path) {
 			super();
 			this.targetPath = path;
 		}
-		
-		public DiscoveryLabel(String path, Instance instance) {
+
+		public DiscoveryLabel(String path, String scheme, Instance instance) {
 			this(path);
 			
 			this.orgName = instance.getTarget().getOrgName();
@@ -64,6 +68,7 @@ public class DiscoveryEndpoint {
 			this.applicationId = instance.getApplicationId();
 			this.instanceNumber = instance.getInstanceNumber();
 			this.instanceId = instance.getInstanceId();
+			this.scheme = scheme;
 		}
 		
 		@JsonGetter("__meta_promregator_target_path")
@@ -105,6 +110,11 @@ public class DiscoveryEndpoint {
 		public String getMetricsPath() {
 			return this.targetPath;
 		}
+
+		@JsonGetter("__scheme__")
+		public String getScheme() {
+			return this.scheme;
+		}
 	}
 	
 	public static class DiscoveryResponse {
@@ -146,7 +156,7 @@ public class DiscoveryEndpoint {
 		for (Instance instance : instances) {
 			
 			String path = String.format(EndpointConstants.ENDPOINT_PATH_SINGLE_TARGET_SCRAPING+"/%s/%s", instance.getApplicationId(), instance.getInstanceNumber());
-			DiscoveryLabel dl = new DiscoveryLabel(path, instance);
+			DiscoveryLabel dl = new DiscoveryLabel(path, this.myScheme, instance);
 			
 			DiscoveryResponse dr = new DiscoveryResponse(targets, dl);
 			result.add(dr);
```

**Comment by dmarmugi** [comment]
A few other notes: 
- This seems related to #189 but it's unclear how that issue was resolved
- I don't think using [`promregator.targets[].protocol`](https://github.com/promregator/promregator/blob/v0.9.1/docs/config.md#item-property-promregatortargetsprotocol-optional) for the `__scheme__` value would work here (or it would work accidentally) because that seems to govern how _Promregator_ communicates with the _targets_ whereas this config parameter would govern how _Prometheus_ communicates with _Promregator_
- A less flexible alternative would probably cover close to 100% of use-cases by doing something like `if myPort == 443, then __scheme__ = "https`

**Comment by eaglerainbow** [comment]
Hi,

Thanks for bringing this up! 
I think I get your problem - and I wouldn't mind too much of changing Promregator here. However, I am asking myself whether it wouldn't be easier to solve this with a configuration change at Prometheus.
I haven't tried it out myself locally, but could you check whether something along the lines of

```
scrape_configs:
  - job_name: "cf_promregator"
    scheme: https
    http_sd_configs:
      - url: https://<promregator>/discovery
        refresh_interval: 15m
    relabel_configs:
    - source_labels: [__scheme__]
      regex: '.*'
      replacement: 'https'
      target_label: '__scheme__'
```
wouldn't also do the trick?
If I get [Prometheus' documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) right, this could also work out...

If that does not lead to success, let's check on your suggested code change 😀

**Comment by eaglerainbow** [comment]
ah, I get your point... You don't like that your configuration is so complicated... mhmm...

But why do you want to introduce another configuration option in Promregator, if another already exists in Prometheus? This just sounds like shifting configuration from left to right...
I mean, if we set `__scheme__` already in the `/discovery`'s JSON document, then you would only save exactly one line in your Prometheus' configuration:

``` 
scrape_configs:
  - job_name: "cf_promregator"
    http_sd_configs:
      - url: https://<promregator>/discovery
        refresh_interval: 15m
```

Or do I still get something wrong?

**Comment by dmarmugi** [comment]
you get my points perfectly
The workaround (modifying the prometheus scraping config) is perfectly valid, it just means I have to make two changes (set `discovery.port:443` and `scheme:https`) in two different systems at the same time. I'm not sure myself whether avoiding this trouble is worth adding a new configuration option -- it wouldn't surprise me at all if you decide it's not 🙂 

I think the relabel_configs you suggest aren't necessary, just adding the `scheme` config at the scrape_config job level is sufficient. 


For context, I think what drove me to create the ticket was largely that there's an un-articulated conflict: Everything in the Promregator docs and code specifies that `https` is the default (for talking to CF, for talking to other instances, etc.), but in Prometheus configs it's actually http that's the default. Here at the service_discovery layers that conflict comes to the fore.

**Comment by eaglerainbow** [comment]
> I think the relabel_configs you suggest aren't necessary, just adding the scheme config at the scrape_config job level is sufficient.

Yes, I agree. 

> Everything in the Promregator docs and code specifies that https is the default (for talking to CF, for talking to other instances, etc.), but in Prometheus configs it's actually http that's the default. Here at the service_discovery layers that conflict comes to the fore.

Yes, this is really the "root cause" for this: Prometheus has to stay compatible with the original defaults, falling back to HTTP. 
Promregator is of newer age and does not have that heritage. 
This boils it down that the provider (here Promregator) should explicitly reconfigure the state, in case it knows better.
For me this means that we should provide such a configuration in Promregator - but the defaulting (to conclude from port `discovery.port: 443` to set scheme to https by default) is the more "important" feature than being able to overwrite the scheme in Promregator's configuration. 
Changing the scheme's defaulting behaviour (from "always http" to "conditionally https") may be considered in incompatible change. It may be rather reasonable to do so (who runs a pure-HTTP server on 443?! Perhaps to confuse the Russians...) and for 99% of the users this new defaulting would be okay and reasonable. 

Which brings us to the question: Do we want to take "the risk of doing an incompatible change"? Is the benefit big enough to justify the risk/costs?

Currently, I would say, yes. 

The only thing which we should do in this case, we should clearly announce that this is an incompatible change and mention it in our "must-know" section of the release notes. Then everyone can be aware of it and check their configuration. 

PS: Too bad that I just released V1.0.0 yesterday. It would have been an easy thing to make this part of the major release - and then we would have been out of any trouble... :confounded:

**Comment by dmarmugi** [comment]
I've got these changes running locally, waiting on my opensource program to give me the green light and I can submit a PR

**Comment by eaglerainbow** [comment]
Thanks! Please let me know in case you need any support on this clarification!

**Comment by eaglerainbow** [comment]
will eventually go into 1.1.0.
