### ISSUE TITLE
Specify Mininum Version for V3 API

### ISSUE THREAD

**Issue by dmarmugi** [promregator/promregator#234]
## Environment
Running v1.0 in various CF sites as a jar

## Summary / Problem Statement
Promregator seems to rely on a feature that was added later to the V3 API (Related to #228)

## Observed Behavior
When scraping targets:
> 2023-03-20T12:56:09.14-0400 [APP/PROC/WEB/1] OUT Caused by: org.cloudfoundry.client.v3.ClientV3Exception: CF-BadQueryParameter(10005): The query parameter is invalid: Unknown query parameter(s): 'app_guids'. Valid parameters are: 'page', 'per_page', 'order_by', 'hosts', 'space_guids', 'organization_guids', 'domain_guids', 'paths', 'include', 'label_selector'

## Expected Behavior
I _believe_ this commit (cloudfoundry/cloud_controller_ng@f186ac4) both adds the `app_guids` parameter being used above, and specifies a workaround. 

I wouldn't say we to implement the workaround, rather I'd just update the docs to specify that there's a minimum V3 API version required to run v1.x. I'm not an operator, so I don't know exactly what version that would be, nor how to verify it :)

**Comment by eaglerainbow** [comment]
Issue is about the `/routes` endpoint, which was added with CF CC [API V3 3.76.0](https://v3-apidocs.cloudfoundry.org/version/3.76.0/#routes). 

Support for app_guids was added with CF CC [API V3 3.84.0](https://v3-apidocs.cloudfoundry.org/version/3.84.0/#list-routes).

**Comment by eaglerainbow** [comment]
API V3 3.84.0 was part of [CAPI 1.94.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.94.0).
CAPI 1.94.0 delivered with [cf-deploy v13.5.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.5.0) on June 20th, 2020.

**Comment by eaglerainbow** [comment]
Hi @dmarmugi ,

Thanks for the pointer and the good suggestions!

> I'm not an operator, so I don't know exactly what version that would be, nor how to verify it :)

So neither am I, but I think I could figure out that 3.84.0 will be the lowest version which will work out.
I have added corresponding documentation information with commit fe039f27936651f6774b87b5207fc51c9cdbbc80. It directly went to `master`, so the documentation, which is rendered by github, will be updated automatically.
