### ISSUE TITLE
Unsure how to configure with https CF API / untrusted HTTPS on CF API Host / Org with missing updatedAt (V3->V2)

### ISSUE THREAD

**Issue by bkez322** [promregator/promregator#36]
I'm working through the Quickstart guide. My CF API exists at https://my.cf.api.com, and my Cloud Foundry is behind a web proxy, so I set up my promregator.yaml like this:

```yaml
promregator:
  authenticator:
    type: none

  targets:
    - orgName: my-org
      spaceName: my-space
      applicationName: my-app

cf:
  api_host: my.cf.api.com
  username: my-username
  proxyHost: http://my.proxy.com
  proxyPort: 8080
```

The intitial startup appears to be fine (I'll share in case there's something helpful here):
[promregator_startup.txt](https://github.com/promregator/promregator/files/1861618/promregator_startup.txt)

Likewise, I can connect to http://localhost:56710 fine.

When I go to connect to http://localhost:56710/metrics I get a generic Spring Boot error page. The logs show this:
[promregator_on_connect_to_metrics.txt](https://github.com/promregator/promregator/files/1861079/promregator_on_connect_to_metrics.txt)

Perhaps, I thought, Promregator is trying to connect to my.cf.api.com over *http* when it should correctly be *https*?

I don't believe there's any options that configure the protocol used to connect to the API.

https://github.com/promregator/promregator/blob/master/docs/config.md#option-promregatorauthenticatortype-mandatory
and
https://github.com/promregator/promregator/blob/master/docs/config.md#item-property-promregatortargetsprotocol-optional
only seem to relate to the scraping process and not the api connection process- or does it apply to both?

I tried explicitly setting the targets protocol to `https` with no change.

Since the documentation on `promregator.authenticator.type` states
```
null or none: Disables any additional authentication scheme; requests will be sent as unauthenticated **HTTP** GET requests. No further options need to be provided
```

I tried changing authenticator.type to basic and provided the same user name and password as I do to cf.username and cf.password, with no change.

I'm unsure how to proceed. Apologies if I'm misunderstanding something about the config documentation.

I also noted that https://github.com/promregator/promregator/blob/master/docs/config.md#option-cfproxyhost-optional states `If you want to make the system establish the connection to the API host using an HTTP (sorry, HTTPS not supported yet) proxy, enter the IP address of this server here`. I interpreted this to mean that I should be able to connect to my https API through my http proxy fine.

**Comment by eaglerainbow** [comment]
> Since the documentation on `promregator.authenticator.type` states [for null...]

There is also a possible misunderstanding, which I tried to address with 566b02e24808480e7d86dc43df892e54ca8a47f9 and 5721681888e59cc52c08ddc0d540c0b62403331b

**Comment by bkez322** [comment]
Likewise, with no proxy defined in the config, I get the same SSL error.

**Comment by eaglerainbow** [comment]
I think with the IP address, we are getting closer now.
The error message if interest for you now reads

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

with which Java wants to tell us that the certificate provided by the CF platform (here the CF API host) cannot be verified against the root certificates in the docker container. Does your API host provide a certificate which is signed by a public CA?

**Comment by bkez322** [comment]
If I set the proxy to anything with HTTP in front of it (e.g. `http://google.com`) Promregator starts up without SSL issues as well, so that would imply it was never actually correctly going through my proxy at any point.

**Comment by bkez322** [comment]
I think you're right, I probably don't need to have the proxy set in the config at all. I'm thinking the problem is that I need to make an insecure connection to the API, which I don't think the config of Promregator currently supports.

**Comment by eaglerainbow** [comment]
> I set the proxy to anything with HTTP in front of it (e.g. http://google.com) Promregator starts up without SSL issues as well, so that would imply it was never actually correctly going through my proxy at any point.

Yes and no...

Having a second glance over your `proxy_host_to_ip.txt`, I recon the following: 
it looks like that during boot up of the CF API Java Library (that's way before you are triggering the `/metrics` request), a connection attempt is already made to the CF platform. I assume that this is the metadata fetch for the UAA server and the version check of the API server. That attempt is already made using the proxy, if available, but apparently it fails silently, if the proxy cannot be reached (to whatever reason). If the proxy is ok, we still stuggle with the (invalid?) certificate of the CF API host.

**Comment by eaglerainbow** [comment]
> I think you're right, I probably don't need to have the proxy set in the config at all. I'm thinking the problem is that I need to make an insecure connection to the API, which I don't think the config currently supports.

Would HTTP-only connection support to the CF API endpoint help you?

**Comment by bkez322** [comment]
Is there not a config option currently to point to a certificate?

**Comment by bkez322** [comment]
I'm certainly authenticating to API fine now. I get this error when hitting `/metrics`.

[error.txt](https://github.com/promregator/promregator/files/1862106/error.txt)

I think my Promregator config is fine. Perhaps something is configured unexpectedly or not correctly about my CF?

**Comment by eaglerainbow** [comment]
I don't think so... this could be related to an improvement, which I recently made on `master`. I gave you the "lastest stuff" in that SNAPSHOT... Let me have another look...

**Comment by eaglerainbow** [comment]
No, you are right. That's really coming from the deserializing of the reply from the platform: The `updatedAt` attribute of the "v3 organization" API call is not filled at all. That's not compliant to the CF API spec and thus the CF API Java library rejects building the result object.
So, in this special case you would really have to talk with the CF platform itself ;-)

**Comment by eaglerainbow** [comment]
Perhaps just rename the org to some new name and back? Usually this should touch the `updatedAt` timestamp, which might already do the trick...

**Comment by bkez322** [comment]
I don't have the ability to easily create or update orgs myself unfortunately. I tried with another org that was  semi-recently created ( a few months ago vs years ago).

I get this error:

```
2018-03-29 22:42:34.631  INFO 10 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-03-29 22:42:34.632  INFO 10 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-03-29 22:42:34.644  INFO 10 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 12 ms
2018-03-29 22:42:34.688  INFO 10 --- [nio-8080-exec-1] Query Org                                : | onSubscribe([Fuseable] FluxOnAssembly.OnAssemblySubscriber)
2018-03-29 22:42:34.690  INFO 10 --- [nio-8080-exec-1] Query Org                                : | request(unbounded)
2018-03-29 22:42:35.072  INFO 10 --- [ry-client-nio-3] Query Org                                : | onNext(ListOrganizationsResponse{pagination=Pagination{first=Link{href=https://my.cf.api/v3/organizations?names=DIFFERENT-ORG&page=1&per_page=50, method=null}, last=Link{href=https://my.cf.api/v3/organizations?names=DIFFERENT-ORG&page=1&per_page=50, method=null}, next=null, previous=null, totalPages=1, totalResults=0}, resources=[]})
2018-03-29 22:42:35.073  INFO 10 --- [ry-client-nio-3] Query Org                                : | cancel()
2018-03-29 22:42:35.076  INFO 10 --- [ry-client-nio-3] Query Org                                : | onComplete()
2018-03-29 22:42:35.082 ERROR 10 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 0] with root cause

java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454) ~[na:1.8.0_162]
	at org.cloudfoundry.promregator.scanner.ReactiveAppInstanceScanner.lambda$getOrgId$7(ReactiveAppInstanceScanner.java:199) ~[classes!/:0.2.0-SNAPSHOT]
```

This seems to imply it can't find the org. Not sure why- the only "unusual" thing about is the dash in the name.

**Comment by bkez322** [comment]
And I quadruple-checked that its spelled right and exists.

**Comment by bkez322** [comment]
Unfortunately I don't think I'm going to get a user account with access to any orgs other than the first one I tried. What I *do* have are CF client credentials with readonly permissions of all orgs/spaces/apps, but I don't think Promregator supports that at this time.

**Comment by eaglerainbow** [comment]
> Unfortunately I don't think I'm going to get a user account with access to any orgs other than the first one I tried. 

What's the current API version of your CF platform? 
It feels strange that there is such an incompatibility on the `updatedAt` attribute. If we can narrow it down somehow, it might be worthwhile to create an issue at https://github.com/cloudfoundry/cf-java-client/issues together.

> What I do have are CF client credentials with readonly permissions of all orgs/spaces/apps, but I don't think Promregator supports that at this time.

That is correct (unfortunately). 
There is a class called `org.cloudfoundry.reactor.tokenprovider._ClientCredentialsGrantTokenProvider` in the CF API (see also https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/_ClientCredentialsGrantTokenProvider.java), but I do struggle a little with what the attribute `identityZoneSubdomain` means in this context (and whether we have to fill it). As I don't have such a pair of credentials for my platforms myself, I also don't stand a chance to try it out myself. Moreover, I am asking myself whether this is a valid authentication scheme for Promregator as a whole, as this is the path to the "technical geeks" route: If you onboard to Bluemix, you won't get such kind of credentials...

**Comment by eaglerainbow** [comment]
Please note that I have deleted the temporary docker image version 0.2.0-SNAPSHOT from hub.docker.com, as version 0.2.0 was just released.

**Comment by bkez322** [comment]
I can check the version later, but I’m guessing the problem is simply that my cf org was created before api-v3 existed, and at that point CF probably wasn’t tracking the updatedAt time the way it is now (though you kind of expect a database to be store that info by default wouldn’t you?)

My rationale is that v2 api for org summary doesn’t give updatedAt, and I know my org dates back to Summer 2016. I’m guessing the workaround you suggested of changing the name and back would fix it. I could possibly get someone to do that with just one org to test that theory, but sorry to say I don’t think  it’s going to be a valid option for me to tell an admin to do that for each of the hundreds of cf orgs we have across dozens of cf deployments.

 http://v3-apidocs.cloudfoundry.org/version/3.41.0/index.html#introduction states that v2 is still primary api for interacting with CF. That’s an incredibly vague statement, but perhaps that implies people shouldn’t be relying on the v3 API quite yet. Or at the very least- a tool like Promregator should maybe be optionally configurable to work exclusively with the v2 api? Just something to consider.

What is the updatedAt field used for anyway?

**Comment by eaglerainbow** [comment]
I see what you mean. My assumption was - so far - that V3 is compatible in all regards to data that was created in V2. Apparently, this is not always the case. `updatedAt` is not used by Promregator in any sense, but the underlying CF API Java client is expecting it mandatorily (to whatever obscure reason). 
Let me see, how we can get out of this trouble...

**Comment by eaglerainbow** [comment]
BTW: the case still is strange, as the `updatedAt` attribute is already available in V2: http://apidocs.cloudfoundry.org/280/organizations/list_all_organizations.html (see there: `resources.metadata.updatedAt`).

**Comment by bkez322** [comment]
Oh you’re right, I was looking at the summary endpoint I think.

**Comment by eaglerainbow** [comment]
Could you do me a favor and send me the output of the last request as of

```bash
$ cf login
[use your CF user's credentials]
$ cf -v orgs 
```
in your case?
I would be interested in what the response is on the `metadata` block of the request `GET /v2/organizations?order-by=name HTTP/1.1` in your case. 
if you fear to expose any internal data of your platform, we can also arrange that you send me the stuff via email directly.

**Comment by eaglerainbow** [comment]
Also the output of `cf api` could be helpful...

**Comment by bkez322** [comment]
[orgs.txt](https://github.com/promregator/promregator/files/1864485/orgs.txt)

```
cf api
api endpoint:   https://api.my.cf.endpoint.com
api version:    2.94.0
```

Probably worth noting is that next_url, prev_url, and updatedAt are all null.

**Comment by eaglerainbow** [comment]
Thanks; at least the stuff is ugly consistently. My head is fuming on what we can do against that...

**Comment by eaglerainbow** [comment]
Mmhm... apparently, V2 organizations isn't that strict on the metadata than the new V3. 
I have created a temporary version which only uses V2 orgs, spaces and apps (but still uses V3 processes - that's a little more tricky to go back to V2 there).
If I uploaded you a 0.3.0-SNAPSHOT to hub.docker.com, would you give it a try?

**Comment by eaglerainbow** [comment]
Temporary version is pushed successfully: `0.3.0-SNAPSHOT`.
Feedback is appreciated!

**DISCLAIMER** (to the rest of the world): The version is only provided temporarily for the sake of testing, whether this could solve the issue here. Don't expect that the version will be available for you, too!

**Comment by bkez322** [comment]
Nice, 0.3.0-SNAPSHOT worked for me. I'm seeing metrics on the `/metrics` endpoint of Promregator. I'll close the issue.

**Comment by bkez322** [comment]
Would still be nice to know that updatedAt became null in the first place though, eh?

**Comment by eaglerainbow** [comment]
Yeah, ... the [folks at cf-java-client](https://github.com/cloudfoundry/cf-java-client/issues/871) are also quite confused about that. The discussion there now is about whose fault this is: the client's or the server's. Bets are accepted 😁 

I will downport the V2 downgrate to the v0.2.x series to make sure that you get something usable soon.

**Comment by eaglerainbow** [comment]
Ok, [0.2.1](https://github.com/promregator/promregator/releases/tag/v0.2.1) is released
