### ISSUE TITLE
API Host configuration

### ISSUE THREAD

**Issue by john717** [promregator/promregator#45]
The documentation says that the configuration file should be setup with a hostname defined for "apiHost".  However, it seems that the expected value is actually "api_host".  

This one is not working and gives this error on startup: _Could not resolve placeholder 'cf.api_host' in value "${cf.api_host}"_

cf:
  apiHost: api.cf.example.org

This one works:

cf:
  **api_host:** api.cf.example.org

**Comment by eaglerainbow** [comment]
Thanks for the pointer. I had switched between both variants back and forth several times, as I was unsure, which one would be the more consistent one. 
The correction is already included in the following branches:

| branch | version series | provided with commit |
|-----|------|------|
| rel-0.2 | 0.2.x | 01a1b7e9b1bb91049bee5e29c2df0a285fb40b84 |
| rel-0.3 | 0.3.x | 41e2c3456d1daedf5c7ea4c43a0d459579683aeb |
| master | 0.4.x and later | ea9fc730ce19f8895f10d2213a441b3d47c2a029 |

In case that you found yet another case, where this (or another) mistake has happened in the documentation, please feel free reopen this ticket (if it's about `api_host`) or create a new issue.

Thanks again!
