### ISSUE TITLE
Feature: Passwords shall not be stored plaintext in config file

### ISSUE THREAD

**Issue by eaglerainbow** [promregator/promregator#62]
## Environment
version 0.4.0 and above

## Summary / Problem Statement / Observed Behavior
Passwords are currently stored unencrypted in the config file.
Caveat: Passing passwords via environment/system variable is permitted, though.

## Expected Behavior
The passwords are either stored encrypted or at least there is an option to allow that. 

Note that it is not said that storage must still happen in the config file itself. The file for passwords may be externalized.

**Comment by vervas** [comment]
Ideally they could be injected as environment variables.

One way would be one env var per auth id as suggested in the first solution of #60.

The other one would be being able to pass the whole `promregator.targets` array as one env var that is in JSON format, which could merge or override what is defined in `promregator.yml`.

**Comment by vervas** [comment]
If you would pass an encrypted file, then you would also need to pass an encryption key as an environment variable in order to decrypt the provided credentials.

**Comment by eaglerainbow** [comment]
> If you would pass an encrypted file, then you would also need to pass an encryption key as an environment variable in order to decrypt the provided credentials.

Yeah, but this means 
a) less usability during configuration
and 
b) the problem is just reduced to one password (but in general still remains the same).

**Comment by eaglerainbow** [comment]
> Ideally they could be injected as environment variables.

That is mainly already happening today (see also suggestions provided in the documentation, which says that the passwords shall *not* be stored in the yaml configuration file (though they technically could), but instead shall be set via environment/system variable).

**Comment by eaglerainbow** [comment]
> The other one would be being able to pass the whole promregator.targets array as one env var that is in JSON format, which could merge or override what is defined in promregator.yml.

I think that this would be a little to much: I personally dislike the way how CF passes those complex JSON objects for the `VCAP_SERVICES` et al.  as for something simple like changing a hostname or a username you have to parse the whole enchilada (and the usability of the tools to do so on the command line is more than evil).

**Comment by eaglerainbow** [comment]
Found an idea how to do that: https://blog.novatec-gmbh.de/encrypted-properties-spring/

**Comment by eaglerainbow** [comment]
See also #88 
Note that this PR does not solve everything here: Docker Secrets still needs to be handled.

**Comment by eaglerainbow** [comment]
#88 got merged, so we will have support for spring-encrypted passwords starting with 0.6.0.
Please note that we don't support docker secrets, yet.

**Comment by eaglerainbow** [comment]
b7a2885d365f6ba27734921f66bcfe7a6e3ec85a with first attempt to support docker secrets for ENCRYPT_KEY

**Comment by eaglerainbow** [comment]
If that works, we should have "some sort of integration tests" in place.
This is going to be challenging w.r.t. the build infrastructure.

**Comment by eaglerainbow** [comment]
Documentation on how to use with Docker Secrets is described at 03798cf1d6aa75b8d72cbc847cbbfc01c4d7b85d.

Perhaps the better approach than an integration test would be a small test script covering `promregator.sh`.

**Comment by eaglerainbow** [comment]
Test coverage is created since 38d233ce79051d11267dd2adde37c0e42c4a4a2d
The entire suite of functionality will be available starting with 0.6.0.

This concludes the implementation of this issue.
