### ISSUE TITLE
Error Handling / Resillience

### ISSUE THREAD

**Issue by eaglerainbow** [promregator/promregator#65]
## Summary / Problem Statement
In various situations, it turned out that the error handling is not great: We are currently not resilient towards cases like:

* An app got deleted on CF, but we are still trying to scrape it
* The CF Cloud Controller returns non-200 HTTP response codes.

## Observed Behavior
We currently either crash the worker thread and thus do not provide any response (not nice, but ok), or we are currently returning "somewhat dirty data" (not acceptable, as this may lead to data inconsistencies).

## Expected Behavior
Targets, which could not be scraped, should be ignored. If such a case has happened, at the location where the issue has occurred, a corresponding error message in the log should be printed.

Corresponding Unit Test coverage should be available.

**Comment by eloo** [comment]
@eaglerainbow 
oh that sounds good.
we are randomly facing scrape issues when the CF-API is not responding properly.
i guess your changes should fix this?

**Comment by eaglerainbow** [comment]
You might have too high expectations 😀 
a) The metadata, the CF Cloud Controller does not send us, can't be guessed by Promregator. So, if some data is missing, then you will miss some targets to scrape. 
b) I only found some cases by chance, and I try to fix them. I am also revisiting some other code locations (via where-used detection of the internal `CFAccessor` API), but there is no guarantee that I'll find all of them.

But yes, in general, I want to address the following two cases:

* We could end up in messing up other targets, if one target's metadata is invalid  (e.g. all the targets coming *after* the messed-up one, may be messed up, too).
* In severe cases of failures by the CF Cloud Connector (e.g. throwing a 500 status code), we currently crash the HTTP worker thread and thus don't answer anything meaningful to Prometheus - the idea there is to continue based on "best-effort" and respond at least for "some of the targets". 

If you have time, you may want to play around with the changes in branch "improveErrorHandling". Feedback is appreciated - as I don't know yet, if what I have there right now is really good solution (but I don't have a significant better approach at hand so far).

PS: Note that this change has a dependency to the stuff done for #64. This implies that the correction can only go into a `v0.5.0` and later. Downporting it to the `v0.4.x` series most likely will be quite cumbersome...

**Comment by eaglerainbow** [comment]
Organizational hint: I just merged "improveErrorHandling" into "master".

**Comment by eaglerainbow** [comment]
@eloo : NB, I have created a `0.5.0-rc1` for you including the changes here to facilitate your testing (if you want to).
I would be interested to hear the results of your tests (that's why I am not closing this issue here, yet).

**Comment by eloo** [comment]
@eaglerainbow okay.. sounds good.. i will it a try ;)

**Comment by eloo** [comment]
so just tested it and now im facing some exceptions.

```
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 2500ms (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:268) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:253) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
```

looks like a new timeout issue for slow requests?

**Comment by eaglerainbow** [comment]
Yep, that looks like a timeout issue of https://github.com/promregator/promregator/blob/704adeae8da3e4bd7231ed290035e8966904689b/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L221 which means that a request to the CF Cloud Controller timed out.
But don't worry: https://github.com/promregator/promregator/blob/704adeae8da3e4bd7231ed290035e8966904689b/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L222 tells to reactor that it should try two more times. So, it may even be the case, that you did not miss anything here (e.g. if the CF Cloud Connector responded properly to the second request). 

The only thing which puzzles me a bit with your error message is the stack trace: It's too short - I would have expected at least that the original command, which was issued, was written.

**Comment by eloo** [comment]
@eaglerainbow yes the stacktrace was way longer :D i will post it here

**Comment by eloo** [comment]
```
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 2500ms (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:268) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:253) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:370) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
```

**Comment by eaglerainbow** [comment]
> is the timeout configurable? 

No, at least not yet.

> or would it make sense to make it configurable?

Can think of. But if a Cloud Connector does not answer within 2.5s, I would say that we have already a big problem anyway.

> and it looks like the retry is not solving the problem.. i nearly get zero metrics scraped

That's a very bad development. As #67 has just been raised for exactly that issue (and this issue here is more about the resilience against errors, I'd suggest to continue the "timeout discussion" over there.

**Comment by eloo** [comment]
@eaglerainbow yeah the interesting point with #67 is that john is facing this issue with 0.4.0
i only having issues with the 0.5 rc

**Comment by eaglerainbow** [comment]
> yeah the interesting point with #67 is that john is facing this issue with 0.4.0
i only having issues with the 0.5 rc

Did I get you right with what you are saying that you **only** face the issues with 0.5.0-rc1, but **not** with 0.4.0?
That would make a major difference...

**Comment by eloo** [comment]
@eaglerainbow couldn't remeber to have this issue with 0.4.0
but immediately after updating to 0.5.0-rc1 i've seen this error

**Comment by eaglerainbow** [comment]
That's weird. If I look at [the delta between 0.4.0 and 0.5.0-rc1](https://github.com/promregator/promregator/compare/e1351c5c52d87f10f2af06f68677f06024012b19...2604928a3d78c6ce4221c1a12c6ad55c7b2eb475) then we have only the changes of this issue here and #64 . The big delta is there the removal of all the calls to domains, routes and such-a-like. However, I would expect that this should make 0.5.0-rc1 more robust, as we have less calls to make to the CF Cloud Controller. You exactly say that the opposite is the case. Moreover, the same effect was also found by @john717 in 0.4.0 (I dunno whether he also has checked 0.5.0-rc1 yet). I'd suggest continuing to discuss that over there....

**Comment by eaglerainbow** [comment]
The problem eloo has reported seems to be the same one as #67. The topic is handled there properly. The initial request of this issue, improving the error handling, has been done (to my mind). And there are no negative reports/issue reported which complain about the current state.

That is why I am closing this issue here. If anyone thinks different, please feel free to re-open it.
