### ISSUE TITLE
promregator is not reflecting the metrics about the app which is deployed on CF.

### ISSUE THREAD

**Issue by lordcf** [promregator/promregator#71]
Hi all,
I have pushed testapp app in our cloud foundry environment as described in quick start docs.
used following command to push app:
cf push testapp -m 1g --random-route -p /home/vicky/myspace/acf-4/TestMetricsApplication.jar
Then its showing data as expected on browser.

Then i have push promregator as a application on our CF using its .jar file.
manifest i have prepared is like : 
# manifest
`---
applications:
- name: promregator
  memory: 1G
  random-route: true
  path: /home/vicky/myspace/acf-4/test-promregator/promregator-0.4.0.jar

promregator:
  metrics:
    internal: true
  authenticator:
    type: none

  targets:
    - orgName: vicky
      spaceName: space-1
      applicationName: testapp
cf:
  api_host: https://api.sys.eu.cfdev.canopy-cloud.com
  skipSslValidation: true
  username: admin
  password: WelkoydChou****vDyHiOwFrou`

---------------------------------------------------------------------------------
when I hit the link provided by cf its not showing data about the application.
when i tried to find discovery metrics : 
`{"__meta_promregator_target_path":"/promregatorMetrics","__meta_promregator_target_orgName":null,"__meta_promregator_target_spaceName":null,"__meta_promregator_target_applicationName":null,"__meta_promregator_target_applicationId":null,"__meta_promregator_target_instanceNumber":null,"__meta_promregator_target_instanceId":null}}]`
 
so why it is not reflecting the orgname , spacename and appname and respected information related to application.

  
# environment:
promregator version:  promregator-0.4.0.jar
cf api version:    2.102.0
cf version : 287

**Comment by eaglerainbow** [comment]
Welcome to promregator.

I tried to understand what you did exactly based on your description. I would have some questions, which we should clarify first:

* The format of your description above is a little distorted and may be ambiguous. Did you write both the targets and the application's CF manifest into one file?
* What does promregator show in its logs?

Promregator by itself is not a CF application - at least out-of-the-box! You may run it as one, e.g. by using the docker container provided, but still you need to take care that your configuration file gets added to the image. All this may become quite complicated, that is why the quickstart documentation recommends you to download the docker image and run it locally (i.e. outside of your CF platform).

How did you start Promregator? With which command line options? 

I hope that these guiding questions might help us to find where exactly you went wrong...

**Comment by eaglerainbow** [comment]
No feedback on this after more three weeks. That is why I am closing this issue here.
In case you want to continue discussion or need further support, please feel free to re-open the issue here.
