### ISSUE TITLE
skipSslValidation for Scraping

### ISSUE THREAD

**Issue by ntrip** [promregator/promregator#80]
Hi,

I am trying to skip SSL Validation. Below is my promregator.yml file setting for CF.

```
cf:
  api_host: api.cf.example.org
  username: myCFUserName
  skipSslValidation: true
```

It is skipping the SSL validation while starting the Promregator as given [here](
        promregator/src/main/java/org/cloudfoundry/promregator/springconfig/CFClientSpringConfiguration.java 
      ) but while scraping the metrics by Promregator I am again getting the below exception :

```
2018-11-21 09:46:10.606  WARN 9 --- [pool-2-thread-1] o.c.p.fetcher.CFMetricsFetcher           : IO Exception while fetching metrics from target server
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I have enabled the DEBUG log and checked it is trying to get the metrics over HTTPS. So I have checked the code of [CFMetricsFetcher](
        promregator/src/main/java/org/cloudfoundry/promregator/fetcher/CFMetricsFetcher.java
      ) class. I believe this line should be modified if I am skipping the SSL validation:

`response = httpclient.execute(httpget); `

Thanks!

Regards,
Neetu

**Comment by eaglerainbow** [comment]
Hi Neetu,

Note that `cf.skipSslValidation` is exactly doing what it is supposed to do:

> Allows to disable the SSL/TLS certificate validation when **talking to the Cloud Foundry API host** at the servers reported via `cf.api_host`. 

Source: https://github.com/promregator/promregator/blob/8055daad7f0f7d02c7d04829f59c3956f19d2236/docs/config.md#option-cfskipsslvalidation-optional

So, as also the prefix `cf` suggests, this option is only there to disable SSL checking when communicating to the CF platform (here the Cloud Controller).  Scraping is another story to that. 

So far, nobody has requested the feature that SSL checks shall also be disabled for scraping as well. That is why I am marking this issue as feature.

As a workaround for the time being, I can suggest to add the CA certificate of your applications to the default-`cacerts` file as used by Java (see [here](https://stackoverflow.com/a/4326346) how this can be done). In the docker images, you may find that at `/etc/ssl/certs/java`.

**Comment by eaglerainbow** [comment]
The answer on stackoverflow isn't as bright as it appears on first glance. https://memorynotfound.com/ignore-certificate-errors-apache-httpclient/ seems to fit better for our case.

I started with a first implementation of some unit tests at branch `skipSslValidationScraping`.
The real problem of all of this is https://github.com/promregator/promregator/blob/739d00bb1b4ced4aa42bbaeb0bdcbe9c713694d4/src/main/java/org/cloudfoundry/promregator/fetcher/CFMetricsFetcher.java#L50 which is static and thus cannot access the (Spring) environment. On the other hand [HC documentation](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html#d5e43) at section 1.2.1 requires us to reuse the httpclient instance as often as possible. These two approaches are contradicting with each other.

**Comment by ntrip** [comment]
Thanks a ton, Nico for the detailed explanation. 

I have added the certificate as given [here](https://stackoverflow.com/questions/4325263/how-to-import-a-cer-certificate-into-a-java-keystore/4326346#4326346) but it is still scraping metrics over https, not sure if the certificate is wrong or I am doing it in a wrong way. Anyway will try to figure out the issue.

Closing the ticket for now. Hope to see this feature in the upcoming version! 👍 

Regards,
Neetu

**Comment by eaglerainbow** [comment]
> I have added the certificate as given here but it is still scraping metrics over https, not sure if the certificate is wrong or I am doing it in a wrong way. Anyway will try to figure out the issue.

I am little confused; you say that ti's "still scraping metrics over https". I take this as if you **don't** want it to scrape it over https. If http was also okay for you (I don't know your environment), then you might be interesting in reading [Item property "promregator.targets[].protocol" (optional)](https://github.com/promregator/promregator/blob/8055daad7f0f7d02c7d04829f59c3956f19d2236/docs/config.md#item-property-promregatortargetsprotocol-optional), which says that (out of security reasons), the default scraping protocol is https (and not http) - but you are able to change this with this option.

> Closing the ticket for now. Hope to see this feature in the upcoming version! 👍

If you want to see that feature, then we have to keep that issue here open: At Promregator we track both enhancements and bugs both with the same tool (only the tagging via labels make the difference). That's why I reopen the ticket here (until at some point in the - hopefully near - future we have that feature released). Otherwise we won't get it for sure... 😀

**Comment by ntrip** [comment]
> If http was also okay for you (I don't know your environment), then you might be interesting in reading [Item property "promregator.targets[].protocol" (optional)](https://github.com/promregator/promregator/blob/8055daad7f0f7d02c7d04829f59c3956f19d2236/docs/config.md#item-property-promregatortargetsprotocol-optional), which says that (out of security reasons) the default scraping protocol is https (and not http) - but you are able to change this with this option.
> 
Thank you sooo much Nico, this is exactly what I want. I don't have the correct certificate yet. I got one certificate, I have added it via update-ca-certificates but it is still not able to scrape the metrics over https so I want to scrape the metrics over http.

> If you want to see that feature, then we have to keep that issue here open: At Promregator we track both enhancements and bugs both with the same tool (only the tagging via labels makes the difference). That's why I reopen the ticket here (until at some point in the - hopefully near - future we have that feature released). Otherwise we won't get it for sure... 😀

I have checked promregator.targets[].protocol is working absolutely fine so I think this functionality gets covered now. So you can close the ticket.

**Comment by eaglerainbow** [comment]
> I have checked promregator.targets[].protocol is working absolutely fine ...

That's great news to hear that I could be of help. 😄 Sometimes it pays off to just write some comments based on pure guess-work 😁 

> ... so I think this functionality gets covered now. So you can close the ticket.

Ok, thanks for the clarification. 
Yet, I'd like to take your problems as pointer and try to improve our documentation. Once I have done that, I'll close the ticket here.

**Comment by eaglerainbow** [comment]
@ntrip Documentation is changed. 
Please feel free to review it at https://github.com/promregator/promregator/blob/fe9244767b0aa7871584bbb0366924f4d06f18e2/docs/quickstart-docker.md and provide feedback, if that would have solved your issue in first place.
