### ISSUE TITLE
Spring config server Integration

### ISSUE THREAD

**Issue by thiyagu19841** [promregator/promregator#87]
I just pushed promregator to PCF and running as spring boot app and reading cf username, password, org, space and so on from application.properties.. I would like to read these properties from spring config server (i.e., centralized location); i just added  below two dependencies into  POM.xml and I am able to start the app, but I am not able to get the metrics from app and getting error 'Sorry, an error has occurred, for which no dedicated message has been developed so far.'  However, I am able to fetch the metrics if I remove below dependencies.. Can you please help me on this..

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>io.pivotal.spring.cloud</groupId>
			<artifactId>spring-cloud-services-starter-config-client</artifactId>
			<version>2.0.0.RELEASE</version>
		</dependency>

Thanks and regards,
Thiyagarajan K.

**Comment by eaglerainbow** [comment]
Hi Thiyagarajan,

Though I see little what Promregator could do to help you here, i would like to give it a try: Actuator and Prometheus aren't really good friends. You might run into double-authentication issues, namely WebSecurity and Actuator management are both enabled on the same port. From what I read I would assume that you have `management.security.enabled` set to `true`. For some cases, this isn't a great idea. Instead, you should give https://docs.spring.io/spring-boot/docs/1.2.0.M1/reference/html/production-ready-monitoring.html#production-ready-customizing-management-server-port a read, where (amongst other ideas) it is recommended that, if the endpoints are already protected, you should set `management.security.enabled` to `false`.
If that doesn't solve the trick, I would suggest that you post your question at https://stackoverflow.com/questions/tagged/spring-boot-actuator, where most likely much more skilled peers are available who might be helping better than I could...
