### ISSUE TITLE
Promregator is not spring boot 2.1 actuator compliant

### ISSUE THREAD

**Issue by erboucherie** [promregator/promregator#93]
Most of spring boot applications use now *actuator 2.1* , where the exposure of metrics has changed since version *2.0* . And Promregator do not recognize those metrics unfortunately

**Comment by eaglerainbow** [comment]
Hi erboucherie,

Welcome to Promregator! 
Thank you for your feedback.
To properly assess the priority, could you elaborate a little on your exact use case?

**Comment by erboucherie** [comment]
Hello , please find bellow an explanation : 

With old version of springboot actuator the exposed metrics are in the format  : 
`jvm_memory_pool_bytes_used{pool="Code Cache",org_name="JCF",space_name="test-apps",app_name="demo-metrics-emitter",cf_instance_id="0d630283-e04c-40f8-9639-66920853affe:0",cf_instance_number="0",} 1.1432768E7
 jvm_memory_pool_bytes_used{pool="Metaspace",org_name="JCF",space_name="test-apps",app_name="demo-metrics-emitter",cf_instance_id="0d630283-e04c-40f8-9639-66920853affe:0",cf_instance_number="0",} 4.0162536E7`

With Springboot **2.1** actuator , the metrics exposure format is different :
 `{names: ["jvm.threads.states","process.files.max","jvm.memory.used","jvm.gc.memory.promoted","jvm.memory.max","jvm.memory.committed","system.load.average.1m","jvm.gc.max.data.size","system.cpu.count","logback.events","http.server.requests","myController.date.requests2","tomcat.global.sent","jvm.buffer.memory.used","tomcat.sessions.created","jvm.threads.daemon","system.cpu.usage","jvm.gc.memory.allocated","tomcat.global.request.max","tomcat.global.request","http.client.requests","tomcat.sessions.expired","jvm.threads.live","jvm.threads.peak","tomcat.global.received","process.uptime","myController.date.requests","tomcat.sessions.rejected","process.cpu.usage","jvm.gc.pause","tomcat.threads.config.max","jvm.classes.loaded","jvm.classes.unloaded","tomcat.global.error","tomcat.sessions.active.current","tomcat.sessions.alive.max","jvm.gc.live.data.size","tomcat.threads.current","process.files.open","jvm.buffer.count","jvm.buffer.total.capacity","tomcat.sessions.active.max","tomcat.threads.busy","process.start.time"]}` . 
And this results in the following error : 
`2019-04-08T08:57:34.949+02:00 [APP/PROC/WEB/0] [OUT] 2019-04-08 06:57:34.949 WARN 23 --- [pool-1-thread-5] o.c.p.fetcher.TextFormat004Parser : Detected metric line without proper metric name: {"names":["jvm.threads.states","process.files.max","jvm.memory.used","jvm.gc.memory.promoted","jvm.memory.max","jvm.memory.committed","system.load.average.1m","jvm.gc.max.data.size","system.cpu.count","logback.events","http.server.requests","myController.date.requests2","tomcat.global.sent","jvm.buffer.memory.used","tomcat.sessions.created","jvm.threads.daemon","system.cpu.usage","jvm.gc.memory.allocated","tomcat.global.request.max","tomcat.global.request","http.client.requests","tomcat.sessions.expired","jvm.threads.live","jvm.threads.peak","tomcat.global.received","process.uptime","myController.date.requests","tomcat.sessions.rejected","process.cpu.usage","jvm.gc.pause","tomcat.threads.config.max","jvm.classes.loaded","jvm.classes.unloaded","tomcat.global.error","tomcat.sessions.active.current","tomcat.sessions.alive.max","jvm.gc.live.data.size","tomcat.threads.current","process.files.open","jvm.buffer.count","jvm.buffer.total.capacity","tomcat.sessions.active.max","tomcat.threads.busy","process.start.time"]}`

**Comment by thestevenbell** [comment]
Here is a sample `build.gradle` showing the two dependencies that tell Spring boot to format metrics for Prometheus.  The metrics become available under `/actuator/prometheus`
`buildscript {
	ext {
		springBootVersion = '2.1.1.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.demo'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}


dependencies {

//	Spring
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.boot:spring-boot-starter-cloud-connectors')
	implementation('org.springframework.boot:spring-boot-starter-actuator')

//	Prometheus
	compile 'io.prometheus:simpleclient_common:latest.release'
	compile('io.micrometer:micrometer-registry-prometheus')

	testImplementation('org.springframework.boot:spring-boot-starter-test')
}
`

**Comment by eaglerainbow** [comment]
@thestevenbell Good point.

@erboucherie What type of metric exposure do you expect to have configured? Your output doesn't look to be compliant to the [Prometheus' data format](https://github.com/prometheus/docs/blob/ad9fcc1b0c13ec199358bab9af6913b2ffab95ac/content/docs/instrumenting/exposition_formats.md) at all...

**Comment by erboucherie** [comment]
Yes totally agree with @thestevenbell . We must add the *micrometer-registry-prometheus* dependency to make the metrics available under the `/actuator/prometheus` endpoint . This format is the one promregator is expected i guess . I was referring to the documentation where the sample application does not provide such endpoint . So i guess , in our case , it's either the promregator documentation that needs to be updated and the sample app as well .

**Comment by eaglerainbow** [comment]
> I was referring to the documentation where the sample application does not provide such endpoint

Now your request finally starts to make sense to me. But which "sample application" do you refer to? 
Do you mean https://github.com/promregator/promregator/blob/4656ad0da79901ec4850f238b78f3e86e983c173/docs/quickstart-docker.md#setup-metrics-generating-cloud-foundry-application item 2 there (a.k.a. `TestMetricsApplication.jar`)? Note that this dummy test application isn't running spring-boot 2.1 (yet) and it is intended to be scraped using the `/metrics` endpoint (and not the `/actuator/prometheus`). 

Could you give me a link where the documentation is refering to the "2.1-broken" application?

**Comment by erboucherie** [comment]
Yes that's the application i was referring to . But i've just tested , and indeed if you set the right endpoint `/actuator/prometheus` in the promregator config , it works fine . So this issue can be closed .

**Comment by eaglerainbow** [comment]
> if you set the right endpoint /actuator/prometheus in the promregator config

I still think that the "right endpoint" is `/metrics` and not `/actuator/prometheus`.

> it works fine . So this issue can be closed .

Fine if that all solved your problem, though!

**Comment by erboucherie** [comment]
No , if you set the `/metrics` endpoint with a 2.1 Springboot application , it won't work . As i 'm telling above , the `/metrics` endpoint provides a different format which is not the one expected by promregator

**Comment by eaglerainbow** [comment]
Are we talking about the same thing?
I am talking about exactly the `TestMetricsApplication.jar` file, which is a spring-boot 2.0 application (written by me some time ago) downloadable at https://github.com/promregator/promregator/releases/tag/v0.1.0 .
That application has a special server running, which serves the endpoint at `/metrics` (using the prometheus java standard client). I have one instance running at `https://promregator-scrapetest.eu-gb.mybluemix.net/metrics` and I can see Prometheus metrics there as I write:
``` 
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 1.8711592E7
jvm_memory_bytes_used{area="nonheap",} 4.058032E7
# HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
[...]
``` 

You may be right that in the general sense: If SpringBoot-2.1 applications also do expose a `/metrics` endpoint, it may (by default) be in a wrong format. But that is not related to Promregator at all, as Promregator clearly states that it is only used for Prometheus-formatted endpoints and expects the path of an application mentioned in the configuration to comply to that very same format. If not, this is a misconfiguration.

**Comment by erboucherie** [comment]
Ok then we agree . Yes if it's clearly well documentated that promregator works with **Prometheus-formatted endpoints** , then it's fine either the app is Springboot 2.0 or 2.1 . It will be the developer responsability to configure properly the endpoint . Sorry for the misunderstanding .

**Comment by eaglerainbow** [comment]
Okay, thanks.
I tried to stress it even more clearly now in the documentation (changed with 4186606). 
Please feel free to comment in case it still might be misunderstandable (in that case I am totally happy to reopen this ticket).

**Comment by eaglerainbow** [comment]
Note to myself: the issue reported in #100 cannot be the reason for sending large amounts of org requests in such a short time frame: `resolveOrg` uses a String as key for the map.

**Comment by datumgeek** [comment]
for the above (probably stating the obvious)...  you need this in your properties file:

```
endpoints:
  prometheus:
    enabled: true
```
