### ISSUE TITLE
Mistaken config YAML: applicationName considered to be a list

### ISSUE THREAD

**Issue by thestevenbell** [promregator/promregator#98]
## Environment
- Docker image: promregator/promregator:0.5.7
- Cloud Foundry platform API version: 2.112.0)

## Summary / Problem Statement
All applications for a given Org and Space are being scraped even though a specific application is defined in the <targets> stanza.  

## Observed Behavior
Configuring a single application within the targets stanza of the configuration file does not prevent all applications within the space and org from being scraped by Promregator.  Example configuration:
```  
targets:
    - orgName: Inventory
      spaceName: tools
      applicationName: 
        - slo-metrics
```
## Expected Behavior
It is expected that when an application name is given that only that application will be scraped but instead all of the applications are being scraped.  The logs show 404 errors for each application in the space that does not have a /metrics endpoint.
From the docs on this site:
```
#### Item property "promregator.targets[].applicationName" (optional)
Specifies the name of the Cloud Foundry Application (within the Cloud Foundry Organization and Space specified above), which hosts the application, which you want to query for metrics.

To ensure consistency with the behavior of many Cloud Foundry implementations, the name is treated case-**in**sensitively since Promregator version 0.5.0.

If left out (and also "applicationRegex" is omitted), *all* applications within the specified Cloud Foundry Organization and Cloud Foundry Space are considered as targets. Only applications in the Cloud Foundry Application state "STARTED" are considered.
```

**Comment by eaglerainbow** [comment]
Hi
`applicationName` is not an array - it's a single literal. Note the notation is `promregator.targets[].applicationName` and not `promregator.targets[].applicationName[]`.
Please also see my comment in #97 on this.

**Comment by thestevenbell** [comment]
Understood.  Thank you for the help.  It is clear in the documentation.

**Comment by eaglerainbow** [comment]
> Understood. Thank you for the help. It is clear in the documentation.

Is there anything the documentation could have done better/differently such that you wouldn't have fallen into that trap the first time?

**Comment by eaglerainbow** [comment]
Given that there was no reply for more than 3 months on this issue, I'll close it. If you still want to provide feedback, please feel free to do so.
